# -*- coding: utf-8 -*-
"""how_used_pre-trained_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11qTQ_EUEG5sORCh-b3dZ9K4zMnp6CUG_
"""

!pip install datasets
!pip install librosa

from datasets import load_dataset,Audio
from transformers import pipeline

minds = load_dataset("PolyAI/minds14", "en-AU", split="train")

minds

minds = minds.cast_column("audio", Audio(sampling_rate=16_000))
minds[0]

"""# 1 - Audio classification with a pipeline"""

classifier = pipeline("audio-classification", model="anton-l/xtreme_s_xlsr_300m_minds14")

example = minds[0]

classifier(example["audio"]["array"])

id2label = minds.features["intent_class"].int2str

id2label(example["intent_class"])

"""# it's perfect

# 2- Automatic speech recognition with a pipeline
"""

asr = pipeline("automatic-speech-recognition")

asr(example["audio"]["array"])

"""### The model seems to have done a pretty good job at transcribing the audio!

# 3- Audio generation with a pipeline
"""

pipe = pipeline("text-to-speech")

text = "Ladybugs have had important roles in culture and religion, being associated with luck, love, fertility and prophecy. "
output = pipe(text)

from IPython.display import Audio

Audio(output["audio"],rate = output["sampling_rate"])

"""### you can also specify parameter max_token"""

forward_params = {"max_new_tokens": 512}
model = pipeline("text-to-speech",model="facebook/musicgen-small")

text= "im ahmed mahmoud ali from menofy"
output = model(text,forward_params=forward_params)
print(output)
Audio(output["audio"],rate = output["sampling_rate"])

"""### you can pass additional params as **keyward

# Specrogram
"""

example = minds[0]

example





# example = list(ds_head)[-1]  if you use streming mode